### ISSUE TITLE
Restart Loop reading journal logs

### ISSUE THREAD

**Issue by SleepyBrett** [ledbettj/systemd-journal#61]
I'm running fluentd with the systemd-journal plugin. After running fine for few days, fluentd keeps crashing with the below error:

```
2016-05-02 22:59:23 +0000 [error]: unexpected error error="Invalid argument"
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/systemd-journal-1.2.2/lib/systemd/journal/navigable.rb:107:in `seek'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-systemd-0.0.2/lib/fluent/plugin/in_systemd.rb:23:in `configure'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:150:in `add_source'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:91:in `block in configure'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:88:in `each'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/root_agent.rb:88:in `configure'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:117:in `configure'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/engine.rb:91:in `run_configure'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:515:in `run_configure'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:146:in `block in start'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:352:in `call'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:352:in `main_process'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:325:in `block in supervise'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:324:in `fork'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:324:in `supervise'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/supervisor.rb:142:in `start'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/command/fluentd.rb:171:in `<top (required)>'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/bin/fluentd:6:in `<top (required)>'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2016-05-02 22:59:23 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2016-05-02 22:59:23 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2016-05-02 22:59:23 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2016-05-02 22:59:23 +0000 [info]: process finished code=256
2016-05-02 22:59:23 +0000 [error]: fluentd main process died unexpectedly. restarting.
2016-05-02 22:59:23 +0000 [info]: starting fluentd-0.12.20
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.3.1'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-plugin-aws-elasticsearch-service' version '0.1.4'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-plugin-docker_metadata_filter' version '0.1.1'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.4.0'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '0.16.0'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-plugin-mongo' version '0.7.12'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.4'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-plugin-s3' version '0.6.5'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-plugin-scribe' version '0.10.14'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-plugin-systemd' version '0.0.2'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-plugin-td' version '0.10.28'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.2'
2016-05-02 22:59:24 +0000 [info]: gem 'fluent-plugin-webhdfs' version '0.4.1'
2016-05-02 22:59:24 +0000 [info]: gem 'fluentd' version '0.12.20'
2016-05-02 22:59:24 +0000 [info]: adding match pattern="fluent.**" type="null"
2016-05-02 22:59:24 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2016-05-02 22:59:27 +0000 [info]: adding match pattern="**" type="aws-elasticsearch-service"
2016-05-02 22:59:30 +0000 [info]: adding source type="tail"
2016-05-02 22:59:30 +0000 [info]: adding source type="systemd"
```

For reference here is our dockerfile:
https://github.com/Nordstrom/docker-fluentd-aws-elasticsearch/blob/master/Dockerfile

**Comment by dhawal55** [comment]
More details on the above issue:
OS: CoreOS beta 1010.1.0
Systemd: v225

**Comment by ledbettj** [comment]
Hi,

Thanks for the report.  I'm not familiar with fluent or the plugin;  however what it looks like is happening from the above log (If I had to guess) is that an invalid value is being passed into [`sd_journal_seek_cursor`](https://github.com/systemd/systemd/blob/47005cf1cf3a3602b6793973959a0e86fd295eab/src/journal/sd-journal.c#L947-L1050) causing it to return `EINVAL`.    Without knowing what is being passed in, it's hard to say, but let's guess it's a blank string and it's failing the [`isempty()`](https://github.com/systemd/systemd/blob/47005cf1cf3a3602b6793973959a0e86fd295eab/src/journal/sd-journal.c#L962) check.

There's not really anything we can do at this level to prevent this error -- the right thing to do is propagate it up the stack.  I see you also filed https://github.com/reevoo/fluent-plugin-systemd/issues/6 which is the right place to fix this I would guess.  I'm happy to follow the discussion there and see if we need to make any changes here.

With that said, it would certainly be helpful if the gem provided you with a bit more context when raising the error.  That's something that could certainly be added.

**Comment by dhawal55** [comment]
Thanks a lot @ledbettj for looking into this. The pos file where fluentd records the position it last read is empty so most probably it is passing an empty or nil value. I will follow it up at [https://github.com/reevoo/fluent-plugin-systemd/issues/6](url)

**Comment by ledbettj** [comment]
Looks like this was closed in fluent plugin, closing here 💤
